# Generated by Django 5.2.4 on 2025-07-27 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('real_date_added', models.CharField(default='1404/05/05', max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('hour_added', models.IntegerField(default=10)),
                ('code', models.CharField(max_length=10)),
                ('descript', models.TextField()),
                ('show_in_list', models.BooleanField(default=True)),
                ('owner_com_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_c', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_exit', models.IntegerField(default=10)),
                ('date_exit', models.CharField(default='1404/05/05', max_length=15)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_com', to='checking.commodity')),
                ('owner_com_d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_d', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('real_date_added', models.CharField(default='1404/05/05', max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('hour_added', models.IntegerField(default=10)),
                ('number_phone', models.CharField(default='09', max_length=11)),
                ('pearson_code', models.CharField(max_length=10)),
                ('pearson_post', models.CharField(default='', max_length=60)),
                ('origin_place', models.CharField(default='تبریز', max_length=30)),
                ('show_in_list', models.BooleanField(default=True)),
                ('owner_gue_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gue_c', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_exit', models.IntegerField(default=10)),
                ('date_exit', models.CharField(default='1404/05/05', max_length=15)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit', to='checking.guestentry')),
                ('owner_gue_d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gue_d', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inspecter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('real_date_added', models.CharField(default='1404/05/05', max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('hour_added', models.IntegerField(default=10)),
                ('number_phone', models.CharField(default='09', max_length=11)),
                ('pearsone_post', models.CharField(default='', max_length=60)),
                ('origin_place', models.CharField(default='تبریز', max_length=30)),
                ('descript', models.TextField()),
                ('date_exit', models.CharField(default='1404/05/05', max_length=15)),
                ('hour_exit', models.IntegerField(default=10)),
                ('owner_ins_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ins_c', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
