# Generated by Django 5.2.4 on 2025-07-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='hour_added',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='commodityexit',
            name='hour_exit',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='hour_added',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='guestexit',
            name='hour_exit',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='inspecter',
            name='hour_added',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='inspecter',
            name='hour_exit',
            field=models.IntegerField(default=11),
        ),
    ]
