# Generated by Django 5.2.4 on 2025-07-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking', '0002_alter_commodity_hour_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestentry',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
